name: Build Linux

on:
  push:
    tags:
      - 'v*'  # 当推送 v* 标签时触发（如 v1.0.0）
  workflow_dispatch:  # 允许手动触发
  workflow_call:  # 允许被其他 workflow 调用

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [alouette_app, alouette_app_trans, alouette_app_tts]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
      
      - name: Get dependencies
        run: |
          cd ${{ matrix.app }}
          flutter pub get
      
      - name: Build Linux
        run: |
          cd ${{ matrix.app }}
          flutter build linux --release
      
      - name: Create Linux Archive
        run: |
          cd ${{ matrix.app }}/build/linux/x64/release/bundle
          tar -czf ../../../../../${{ matrix.app }}-linux-x64.tar.gz *
      
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app }}-linux
          path: ${{ matrix.app }}/${{ matrix.app }}-linux-x64.tar.gz
