name: Build iOS

on:
  push:
    tags:
      - 'v*'  # 当推送 v* 标签时触发（如 v1.0.0）
  workflow_dispatch:  # 允许手动触发
  workflow_call:  # 允许被其他 workflow 调用

jobs:
  build-ios:
    runs-on: macos-latest
    strategy:
      matrix:
        app: [alouette_app, alouette_app_trans, alouette_app_tts]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Get dependencies
        run: |
          cd ${{ matrix.app }}
          flutter pub get
      
      - name: Build iOS (no codesign)
        run: |
          cd ${{ matrix.app }}
          flutter build ios --release --no-codesign
      
      - name: Create iOS Archive
        run: |
          cd ${{ matrix.app }}/build/ios/iphoneos
          zip -r ../../../${{ matrix.app }}-ios.zip Runner.app
      
      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app }}-ios
          path: ${{ matrix.app }}/${{ matrix.app }}-ios.zip
